### ISSUE TITLE
 Downgrade from ala not working

### ISSUE THREAD

**Issue by adberard** [pbrisbin/downgrade#81] opened 2019-09-15 09:41 UTC
Hello, 
Im currently facing this issue with package installed from the AUR repository (`yay -S`.
```
[I] ➜ DOWNGRADE_FROM_ALA=1 downgrade neovim-nightly

Downgrading from A.L.A. is disabled on the stable branch. To override this behavior, set DOWNGRADE_FROM_ALA to 1 .
See https://wiki.manjaro.org/index.php?title=Using_Downgrade  for more details.
```
Kernel: x86_64 Linux 5.2.11-1-MANJARO
Shell: zsh 5.7.1 (It doesnt work with bash either)

**Comment by pbrisbin** [comment] 2019-09-16 12:53
Hmm, I don't have any kind of message like that in `downgrade` itself:

```console
% g grep 'is disabled on the stable branch'
% 1
```

So this seems to be something Manjaro is doing on top of my script. They must be setting `DOWNGRADE_FROM_ALA=0` somewhere, since the default behavior of `downgrade` is to indeed try the ALA. My _guess_ is they're doing it somewhere that is still being picked up even when you invoke it with `DOWNGRADE_FROM_ALA=1` on the command-line. Maybe try adding an `export` somewhere instead (e.g. `~./.zshrc`)?

Either way, I suggest you seek help by some Manjaro-specific avenue -- closing as not a downgrade issue.

**Closed by pbrisbin** 2019-09-16 12:53 UTC

**Comment by wleoncio** [comment] 2020-09-21 07:44
Can confirm isolation of the problem to Manjaro. Installing downgrade from the community repo yields the message from OP plus a link to https://wiki.manjaro.org/index.php?title=Using_Downgrade.

Unfortunately, for some reason the suggestion of setting `DOWNGRADE_FROM_ALA=1` did nothing for me.

This was however fixed by installing downgrade from AUR (e.g. with `yay -Sa downgrade`).

**Comment by NielsSt** [comment] 2020-10-08 18:22
I can confirm wleoncios comments.

Best Regards

**Comment by Luc45** [comment] 2020-10-29 11:45
Same issue here. I'm running `DOWNGRADE_FROM_ALA=1 downgrade <package>` and still getting the message: 

```
Downgrading from A.L.A. is disabled on the stable branch. To override this behavior, set DOWNGRADE_FROM_ALA to 1 .
See https://wiki.manjaro.org/index.php?title=Using_Downgrade  for more details.

Unable to downgrade <package>
```

OS Info:

```
cat /etc/os-release 
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```

downgrade 8.1.1

**Comment by Luc45** [comment] 2020-10-29 11:51
Installing from AUR as @wleoncio suggested worked. That issue is present in the official repositories from Manjaro.

**Comment by pbrisbin** [comment] 2020-10-29 13:10
I'm going to go ahead and lock this conversation. This is a Manjaro issue, so please seek any support, and centralize any further discussion, in one of their communication channels.
